services:
    greywolfs_fine_diff.twig.extension:
        class: Greywolfs\FineDiffBundle\Twig\Extension\DiffExtension
        arguments:
            - # from config: greywolfs_fine_diff.default_granularity
        tags:
            - { name: twig.extension }
