services:
    webtown_php_fine_diff.twig.extension:
        class: WebtownPHP\Bundle\FineDiffBundle\Twig\Extension\DiffExtension
        arguments:
            - # from config: webtown_php_fine_diff.default_granularity
